USE playground;
CREATE TABLE `USER` (
	`id`	INT	NOT NULL    AUTO_INCREMENT PRIMARY KEY,
	`status`	ENUM('active','deactive')	NOT NULL	COMMENT 'active,deactive',
	`name`	VARCHAR(10)	NOT NULL,
	`email`	VARCHAR(30)	NOT NULL	COMMENT 'ID 역할',
	`password`	CHAR(72)	NOT NULL,
	`create_dt`	DATETIME	NOT NULL	DEFAULT NOW(),
	`update_dt`	DATETIME	NOT NULL	DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP,
	`delete_dt`	DATETIME	NULL	COMMENT '유저 삭제 시 삭제 일시 기록'
);

CREATE TABLE `CHATROOM` (
	`id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`user_count`	INT	NOT NULL	DEFAULT 0,
	`create_dt`	DATETIME	NOT NULL	DEFAULT NOW(),
	`update_dt`	DATETIME	NOT NULL	DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `CHAT` (
	`id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`chatroom_id`	INT	NOT NULL,
	`user_id`	INT	NOT NULL,
	`content`	VARCHAR(1000)	NOT NULL	DEFAULT '',
	`create_dt`	DATETIME	NOT NULL	DEFAULT NOW(),
	`update_dt`	DATETIME	NOT NULL	DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `FRIEND` (
	`id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`user_id`	INT	NOT NULL,
	`friend_id`	INT	NOT NULL,
	`create_dt`	DATETIME	NOT NULL	DEFAULT NOW(),
	`update_dt`	DATETIME	NOT NULL	DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE `USER_PROFILE` (
	`id`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`user_id`	INT	NOT NULL,
	`nick`	VARCHAR(12)	NOT NULL,
	`phone_num`	VARCHAR(15)	NOT NULL,
	`gender`	CHAR(1)	NOT NULL	DEFAULT 'M',
	`image_url`	VARCHAR(500)	NULL,
	`background_url`	VARCHAR(500)	NULL
);

CREATE TABLE `CHATROOM_MEMBER` (
	`chatroom_id`	INT	NOT NULL,
	`user_id`	INT	NOT NULL ,
	`create_dt`	DATETIME	NOT NULL	DEFAULT NOW(),
	`update_dt`	DATETIME	NOT NULL	DEFAULT NOW() ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`chatroom_id`,`user_id`),
    FOREIGN KEY(`chatroom_id`) REFERENCES CHATROOM(`id`) ON UPDATE CASCADE,
    FOREIGN KEY(`user_id`) REFERENCES USER(`id`) ON UPDATE CASCADE
);